### ISSUE TITLE
Rewrite the target adapter

### ISSUE THREAD

**Issue by htollefsen** [transfer-framework/ezplatform#11]
EzPlatformAdapter::send() needs a little bit of rewrite, because the current code is neither pretty nor easily extendable.

**Comment by htollefsen** [comment]
@valisj Would you agree that the cleanup in 2531278989140c0d9dd7be0e033cb9bea41b5521 in #22 is sufficient for the 1.0 release?

**Comment by ghost** [comment]
@htollefsen I think it's fine for the time being.
