### ISSUE TITLE
Ability to define custom fallback language code

### ISSUE THREAD

**Issue by htollefsen** [transfer-framework/ezplatform#32]

**Comment by htollefsen** [comment]
Awaiting https://github.com/transfer-framework/bundle/issues/7.

**Comment by htollefsen** [comment]
Awaiting #88

**Comment by ghost** [comment]
@htollefsen Some issues do not seem to auto-close themselves. Should this issue be closed?

**Comment by htollefsen** [comment]
@valisj We gotta prepend "Solves", "Fixes" etc in the PR description for it to autoclose. Not supported by the new pr-schema, hehe.
