### ISSUE TITLE
Remove versions exceeding versionlimit

### ISSUE THREAD

**Issue by htollefsen** [transfer-framework/ezplatform#35]
Add an EventSubscriber class which recieved an integer defining what is the max number of versions allowed for this content/user/contentype, and remove the oldest version(s).

**Comment by htollefsen** [comment]
Awaiting https://github.com/transfer-framework/bundle/issues/7.

**Comment by ghost** [comment]
@htollefsen Isn't this an eZ Platform issue?

**Comment by htollefsen** [comment]
Kinda. It might be implemented in eZ Platform like it was in eZ Publish, but we don't know when. So I want to investigate if there is a way we can do this ourselves. Because it's so needed when doing imports.

**Comment by ghost** [comment]
@htollefsen Is there an issue on this in eZ's issue tracker?

**Comment by htollefsen** [comment]
@valisj Here https://jira.ez.no/browse/EZP-23281

**Comment by htollefsen** [comment]
[WIP PR](https://github.com/ezsystems/ezpublish-kernel/pull/1811)

**Comment by htollefsen** [comment]
Feature implemented by eZ for >5.4.10. See [doc](https://doc.ez.no/display/EZP/Content+Repository+configuration#ContentRepositoryconfiguration-LimitofarchivedContentitemversions). Closing this.
