### ISSUE TITLE
Import failure when publishing a new version for a content object which is moved to trash

### ISSUE THREAD

**Issue by ghost** [transfer-framework/ezplatform#37]
eZ Platform issues the following error when trying to publish a new version for a content object which has been moved to the trash bin:

```
default.ERROR: Argument '$contentInfo' has a bad state: Content is not published, draft can be created only from published or archived version
```

One possible solution is to use the `TrashService` in order to recover the trashed content object.

**Comment by htollefsen** [comment]
Might be possible to just update `state` of the contentobject aswell.

**Comment by ghost** [comment]
If there are more than one items in the trash, the fix in https://github.com/transfer-framework/ezplatform/issues/52 might fail. 

We have an issue for this here: https://jira.ez.no/browse/EZP-23063
