### ISSUE TITLE
Support for PHP 5.6

### ISSUE THREAD

**Issue by nmeirik** [transfer-framework/ezplatform#45]
Is it intentional that transfer/ezplatform does not support PHP 5.6? When trying to install it on a 5.6 environment I get the following error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for transfer/ezplatform 1.0.x-dev -> satisfiable by transfer/ezplatform[1.0.x-dev].
    - transfer/ezplatform 1.0.x-dev requires php ~5.5|~7.0 -> your PHP version (5.6.16-1~dotdeb+7.1) or value of "config.platform.php" in composer.json does not satisfy that requirement.
```

**Comment by ghost** [comment]
@nmeirik Until this is fixed, use 

```
composer require transfer/ezplatform:1.0.x-dev --ignore-platform-reqs
```

**Comment by nmeirik** [comment]
Thanks!

**Comment by htollefsen** [comment]
Are you still able to reproduce it?

**Comment by nmeirik** [comment]
@htollefsen What do you mean? The requirements seem to remain the same. I did, however, manage to work around it with Valentins `--ignore-platform-reqs` flag, but I don't consider that to address the real issue.

**Comment by htollefsen** [comment]
I tried to reproduce this on both php PHP `5.6.16` and `5.6.13`, without success. Would be great if you could remove your vendor-directory and try again.

**Comment by nmeirik** [comment]
@htollefsen Still same error.

**Comment by htollefsen** [comment]
The ezsystems/ezplatform-demo repo used to have this defined in composer.json:

```
"config": {
    "platform": {       
        "php": "5.4.4"      
    }       
},
```

It was [removed today](https://github.com/ezsystems/ezplatform-demo/commit/9a745853ad6df0316d5c4288eb5f3e751e61defe#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780) and should solve this issue.
