### ISSUE TITLE
Location creation for ContentObject

### ISSUE THREAD

**Issue by nmeirik** [transfer-framework/ezplatform#48]
**_1 Upvote**_ From my point of view, if there was to be any point in passing `Transfer\EzPlatform\Data\ContentObject` objects directly to the eZ Platform adapter (as opposed to the more complex `Transfer\Data\TreeObject`), it would be for the simple creation of a content object with at least one parent location. However, judging from [the Content Manager](https://github.com/transfer-framework/ezplatform/blob/1.0/src/Transfer/EzPlatform/Repository/Manager/ContentManager.php#L126) (and comparing it to [the eZ documentation](https://doc.ez.no/display/EZP/3.+Managing+Content#id-3.ManagingContent-Creatingandpublishing)) it does not seem possible to specify a parent location for an `Transfer\EzPlatform\Data\ContentObject`.

Is this correct? And if so, is this implementation intentional? I realize that the eZ API might support creating content objects without locations, but I'm not sure if I recognize a real world use case for this.

**Comment by ghost** [comment]
We try to keep one-to-one relationship between the core functions in transfer/ezplatform and eZ Platform Public API. Thus, sending `ContentObject` to the adapter will only create eZ content objects and not additional locations.

Everything that is not part of the eZ Platform functionality is introduced via our own concepts such as `TreeObject` (which is handled by both ContentManager and LocationManager at the same time), which is what you would be likely to use for publishing content, unless you need to create content objects and locations separately.

The usage of this Transfer extension will be more clear once we publish a practical example or an extended documentation on these topics.

**Comment by nmeirik** [comment]
> Thus, sending ContentObject to the adapter will only create eZ content objects and not additional locations.

Not sure if I follow this logic. Does this mean that you do not consider [this example](https://doc.ez.no/display/EZP/3.+Managing+Content#id-3.ManagingContent-Creatingandpublishing) (which takes a parameter for the parent locations) to be an integral part of the eZ Public API for the ContentObject?

Also, the TreeObject seems a bit cumbersome when I just want to throw in a couple of objects under a parent (or write a tutorial, for that matter). ;)

**Comment by ghost** [comment]
I wasn't aware of the fact that you could pass a location struct array to content service. :)

@htollefsen I would propose adding a new parameter to `ContentObject`. 

```
$object = new ContentObject(
  (array) $fields, // field values
  (array) $properties, // language, dates, etc.
  (array) $parentLocations, // parent location IDs
);
```

Any thoughts?

**Comment by htollefsen** [comment]
:+1: 

Just a sidenote, if it is going to contain integers (not Locations), lets name it `$parentLocationIds`. :)

**Comment by htollefsen** [comment]
@valisj, do you know how to make use of ParamConverters outside of Symfony? I reckon we'd need som request/response before-events to trigger on the adapter (exists already maybe?). Should we implement it, or only accept Id's for now? We can potentially add support for Location objects later without breaking bc. Thoughts?

**Comment by htollefsen** [comment]
Implemented. You can pass either an array of `integer` or `LocationObject` (or even an eZ Location), or a mix of these.

E.q.:

```
new ContentObject(
    array(
        field1 => value1,
        ...
    ),
    array(
        'parent_locations' => array(
            2,
            new LocationObject(array(
                'parent_location_id' => 43,
            )),
            47,
        )
    )
);
```

Feel free to reopen if you have more related questions.
