### ISSUE TITLE
Misleading location_id property name expected for TreeObject

### ISSUE THREAD

**Issue by nmeirik** [transfer-framework/ezplatform#49]
It seems misleading to me that the eZ Platform Adapter expects an instance of `Transfer\Data\TreeObject` to have a property named `location_id` which will be used as the parent location id when [publishing the object and associated location](https://github.com/transfer-framework/ezplatform/blob/1.0/src/Transfer/EzPlatform/Repository/ContentTreeService.php#L53). 

Shouldn't this be `parent_location_id` instead?

**Comment by ghost** [comment]
This (and many other things) has been bugging me for some time, as well. Thanks for pointing this out! I'll add this to the 1.0 milestone.

**Comment by htollefsen** [comment]
The key was changed to `parent_location_id` last week.
