### ISSUE TITLE
Improve and stabilize DataObject API

### ISSUE THREAD

**Issue by ghost** [transfer-framework/ezplatform#50]
- [x] TreeObject
- [x] ContentObject

**Comment by ghost** [comment]
Related #49

**Comment by ghost** [comment]
Related #48

**Comment by htollefsen** [comment]
Hopefully https://github.com/ezsystems/ezpublish-kernel/pull/1631 will be merged in the near future, if not we'll do the extra loadLocation (as it doesn't create too much overhead) to check ourselves.

**Comment by ghost** [comment]
@htollefsen :+1:
