### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by ghost** [transfer-framework/ezplatform#54]
@htollefsen Are we ready to release the first stable version or should we tag it with something like BETA first?

**Comment by htollefsen** [comment]
@valisj Not yet, IMO. I'm planning on doing some more tests with a proper eZPlatform installation, to see that the result is actually valid. I'd prefer if we only tag it as a beta for now.

**Comment by ghost** [comment]
@htollefsen Ok, I'll create a beta tag.
